# Project information
site_name: AppFit Developer Center
site_url: https://developer.appfit.io
site_author: AppFit
site_description: >-
    Developer resources for AppFit analytics platform.

# Repository
repo_name: appfit-sdk-docs
repo_url: https://github.com/uptech/appfit-sdk-docs
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 AppFit &amp; Uptech Studio. 

nav:
  - AppFit: 'https://appfit.io/'
  - SDK Overview:
    - Overview: index.md
    - Swift: swift/index.md
    - Flutter: flutter/index.md
    - Kotlin: kotlin/index.md

# Configuration
theme:
  name: material
  # custom_dir: overrides
  icon:
    repo: fontawesome/brands/github

  # Static files
  # static_templates:
  #   - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  highlightjs: true
  hljs_languages:
    - swift
    - dart
    - kotlin
    - javascript
    - typescript
  
  language: en
  features:
    - content.code.copy # enables code copy to clipboard feature
    - content.action.edit # adds edit icon to pages
    - content.action.view # adds view page source icon to pages
    #- announce.dismiss # this feature is perenially buggy, so keep it disabled unless necessary.
    - content.code.annotate # enables code annotation feature
    - content.tooltips #enables enhanced tooltips
    - content.tabs.link #links tabs with the same name, so when one is clicked, the others on the same page focus on matching tabs
    # - header.autohide
    # - navigation.expand # expands everything in nav. Not enabled intentionally it's really overwhelming.
    - navigation.instant #makes site act like a SPA. Preserves search index on navigation and saves a bunch of time. Keeps site snappy.
    - navigation.path # enables breadcrumbs
    - navigation.indexes # enables attaching a page to section head: the "index" pages
    - navigation.sections # top-level sections are rendered in groups in the sidebar
    - navigation.tabs # adds the top level menu tabs in the header bar.
    # - navigation.tabs.sticky
    - navigation.top # back to top button
    - navigation.tracking # URL in the address bar is automatically updated with the active anchor as highlighted in the table of contents.
    - search.highlight # highlights search term on page
    - search.share # allows users to share a deeplink to search results
    - search.suggest # enables search suggestions
    # - toc.integrate #this is a really noisy feature. Disabled intentionally.

extra_css:
  - stylesheets/extra.css # Amplitude Styles


plugins:
  - search # the search plugin
  - git-revision-date-localized # enables the git revision date functionality, compatible with macros plugin

# Extensions
# When you add or change an extension here, mirror changes in insiders.mkdocs.yml.
markdown_extensions:
  # - admonition # enables 'callout' boxes
  - abbr # Enables the ability to add a small tooltip to an element, by wrapping it with an abbr tag. Only plain text (no markup) is supported. Use with the "abbreviations" includes file
  - attr_list # Enables adding HTML attributes and CSS classes to almost every Markdown inline- and block-level element with a special syntax.
  - def_list # Enables definition lists (more commonly known as description lists – dl in HTML. https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists
  - footnotes # Enables adding inline syntax to create footnotes
  - meta # enables page metadata
  - md_in_html # enables writing Markdown inside of HTML. Required for Grids and a few other features.
  - tables # Enables Markdown tables
  - toc: # configures the page TOC (righ-side navigation)
      permalink: true
      title: "On this page"
      toc_depth: 3
      permalink_title: Link to this section
  - pymdownx.arithmatex: # preserves LaTeX math equations for use with MathJax
      generic: true
  - pymdownx.betterem: # improves the detection of Markup to emphasize text with special characters (bold and italic text)
      smart_enable: all
  - pymdownx.caret # Enables superscripts
  - pymdownx.details # Enables collapsible admonitions
  - pymdownx.highlight: # Enables code block syntax highlighting
      #anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite # Enables syntax highlighting of inline code blocks
  - pymdownx.keys # Enables inline key display
  - pymdownx.mark # used with carat and tilde to allow marking content (https://squidfunk.github.io/mkdocs-material/reference/formatting/#highlighting-text)
  - pymdownx.snippets # Enables snippets (content reuse)
  - pymdownx.smartsymbols # Enables converting some sequences of characters into their corresponding symbols
  - pymdownx.superfences: # Enables nestable codeblocks
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # Enables content tabs
      alternate_style: true
  - pymdownx.tasklist: # Enables task lists
      custom_checkbox: true
  - pymdownx.tilde # enables strikthrough (<del> tags) and subscripts https://facelessuser.github.io/pymdown-extensions/extensions/tilde/
