name: Deploy Documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and deploy mkdocs site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    - run: pip install -r requirements.txt

    - name: Build Site
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    - run: mkdocs build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Uploading to S3
      run: |
        aws s3 sync ./site/ s3://developer.appfit.io --delete