name: Deploy Documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and deploy mkdocs site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      uses: jannekem/run-python-script-action@v1.7
      with:
        script: |
          python -m pip install --upgrade pip
          pip install requirments.txt

    - name: Build Site
      uses: jannekem/run-python-script-action@v1.7
      with:
        script: |
          python -m pip install --upgrade pip
          mkdocs build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Uploading to S3
      run: |
        aws s3 sync ./site/ s3://developer.appfit.io --delete